name: lab_2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.12
  http: ^1.1.0

  # Feature dependencies
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.3
  connectivity_plus: ^6.1.0
  gradient_borders: ^1.0.2

  # BLoC È™i State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  web: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/